### ISSUE TITLE
User's tiles should come first

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#70]
Right now, the directory tiles are showing up before the user's tiles. The user's tiles should come first.

**Comment by mzhilyaev** [comment]
Marcos, 

it could be because tiles get default frecency of 1000, while if you just click a link on a page the page downloaded get frecency 100.  So, it takes a long while before directory tiles get pushed down by mature history.   I am not sure if this relates to remote-newtab anymore, but that's exactly what's going on in the old newtab

**Comment by marcoscaceres** [comment]
Hey, sorry if you got a blank reply to this... Mail.app screwed up. Unfortunately, I won't be able to today or next week. I'm moving to Australia next week and flying back to Toronto today from NOLA. However, Olivier has kindly agreed to walk you through it. Otherwise, week after next I would be happy to give you an overview of the new stuff.

**Comment by marcoscaceres** [comment]
Ah, makes sense... Yes, on refresh, the tile gets moved to the appropriate spot. 

Closing a WFM.
